### PR TITLE
Full structure, basic pages and home page for new website

### PR DESCRIPTION
**Pull request by riandesign**

### CODE REVIEW

**Comment by brianlagunas** [comment]
Thanks for all this work.  Unfortunately, GitHub does not allow the use of PHP.  What functionality is required for the PHP?  There shouldn't be anything data base driven right now.  It can al be static HTML, javascript, and CSS.  Is it possible ot remove the PHP dependencies?

The docs should just link to http://prismlibrary.readthedocs.io/en/latest/

For now it can just be a single page until I can fill the content, but I can take care of that.

**Comment by riandesign** [comment]
What if we install it in a Linux server? We could install the website in a server that I rent, for example. I wouldn't charge of course.

It's important to keep it in PHP because I already developed all stuffs, specially the languages (japanes/english) and friendly URLs, for example. And if we need to add more contents, it'd be so much easier.

If you want, I can install in my server. If you prefer another one, there is no problem.
Please, let me know what you think about it.

**Comment by brianlagunas** [comment]
Thank you for your offer, but it is important that the Prism team control all aspects of the website.  This is really important for the .NET Foundation.  The intent was to host the website on GitHub.io using this repo.  I'll see what can be done.  The site will not have any real dynamic content, so a static html site would do just fine.

**Comment by riandesign** [comment]
I see. In this case, I will translate the pages to static HTML in a couple of days, ok?
As soon as I do it, I send you a PR.

**Comment by brianlagunas** [comment]
that would be great.  Thank you for all your effort.

**Review by brianlagunas — CHANGES_REQUESTED** [review]
Can you put the "images/prism-logo-graphic-128.png" image back. That image is used for the Prism TemplatePack.

**Review by brianlagunas — APPROVED** [review]

**Comment by brianlagunas** [comment]
Perfect!  Thanks so much for your hard work.

**Comment by riandesign** [comment]
Anything you need, please tell me.

**Comment by brianlagunas** [comment]
Just noticed the images for the View on GitHub and Documentation buttons are missing.

**Pull request merged**
